// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"github.com/mrpsousa/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// AccountGateway is an autogenerated mock type for the AccountGateway type
type AccountGateway struct {
	mock.Mock
}

// FindById provides a mock function with given fields: id
func (_m *AccountGateway) FindById(id string) (*entity.Account, error) {
	ret := _m.Called(id)

	var r0 *entity.Account
	if rf, ok := ret.Get(0).(func(string) *entity.Account); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(*entity.Account)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: account
func (_m *AccountGateway) Save(account *entity.Account) error {
	ret := _m.Called(account)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Account) error); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
