// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/mrpsousa/internal/entity"
)

// ClientGateway is an autogenerated mock type for the ClientGateway type
type ClientGateway struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *ClientGateway) Get(id string) (*entity.Client, error) {
	ret := _m.Called(id)

	var r0 *entity.Client
	if rf, ok := ret.Get(0).(func(string) *entity.Client); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(*entity.Client)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: client
func (_m *ClientGateway) Save(client *entity.Client) error {
	ret := _m.Called(client)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Client) error); ok {
		r0 = rf(client)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
