// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	events "github.com/mrpsousa/pkg/events"
	mock "github.com/stretchr/testify/mock"
)

// EventHandlerInterface is an autogenerated mock type for the EventHandlerInterface type
type EventHandlerInterface struct {
	mock.Mock
}

// Handle provides a mock function with given fields: event
func (_m *EventHandlerInterface) Handle(event events.EventInterface) {
	_m.Called(event)
}
